# -*- coding: utf-8 -*-
"""AI_Resume_Screening.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wuCBvpiEgc8rE_h5RTaOmUEXr9QdwYl

Libraries
"""

import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics.pairwise import cosine_similarity

nltk.download('stopwords')
nltk.download('punkt')

"""Dataset"""

df = pd.read_csv("/content/ResumeDataSet.csv")

df.head()

"""NLP Preprocessing"""

import nltk
nltk.download('punkt_tab')

stop_words = set(stopwords.words('english'))

def preprocess(text):
  text = text.lower()
  words = word_tokenize(text)
  words = [w for w in words if w.isalnum()] #remove symbols
  words = [w for w in words if w not in stop_words]
  return " ".join(words)

df['cleaned_resume'] = df['Resume'].apply(preprocess)

"""Job Description"""

job_description = """
Looking for a data scientist with skills in python, machine learning,
deep learning, pandas, numpy, data analysis, and statistics.
"""

job_description = preprocess(job_description)

"""Filter by Category"""

filtered_df = df[df['Category'] == "Data Science"].copy()

all_texts = filtered_df['cleaned_resume'].tolist() + [job_description]

tfidf_matrix = tfidf.fit_transform(all_texts)

job_vector = tfidf_matrix[-1]

scores = cosine_similarity(tfidf_matrix[:-1], job_vector)

filtered_df['score'] = scores * 100

filtered_df = filtered_df.sort_values(by='score', ascending=False)

filtered_df[['Category', 'score']].head(10)